spring:
  data:
    mongodb:
      database: health_sync
      uri: mongodb+srv://foodie:foodie@cluster0.t4mq9fc.mongodb.net/health_sync
#      uri: mongodb+srv://foodieconnect:foodieconnect@cluster0.t4mq9fc.mongodb.net/health_sync
  application:
    name: PatientRecordService
server:
  port: 8080
  servlet:
    context-path: /api/patient-record-service

