spring:
  data:
    mongodb:
      database: health_tech
      uri: mongodb+srv://kavindyarajapakshabcspgd:YLid69KODEIK7RaU@cluster0.ts8wj.mongodb.net/health_tech
  application:
    name: PatientRecordService
server:
  port: 8080
  servlet:
    context-path: /api/patient-record-service

